name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  # Job to run unit tests
  unit-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_database
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables for testing
        run: |
          echo "DATABASE_HOST=localhost" >> $GITHUB_ENV
          echo "DATABASE_NAME=${{ secrets.TEST_DATABASE_NAME }}" >> $GITHUB_ENV
          echo "DATABASE_USER=${{ secrets.TEST_DATABASE_USER }}" >> $GITHUB_ENV
          echo "DATABASE_PASSWORD=${{ secrets.TEST_DATABASE_PASSWORD }}" >> $GITHUB_ENV
          echo "TESTING=true" >> $GITHUB_ENV

      - name: Run unit tests
        run: |
          pytest tests/test_unit_endpoints.py -v -s  # Runs all tests in the tests directory
